baseURL: /
languageCode: en-us
theme: raditian-free-hugo-theme-data-science
params:
  footer:
    copyright: © Pedro Orden. Todos los derechos reservados.
    site_logo:
      _2x: img/general/business-science-logo.png
      alt: Diseño & Código - Pedro Orden
      x: img/general/business-science-logo.png
  googleAnalyticsID: ''
  logo:
    text1: Orden
    text2: Pedro
  plugins:
    css:
      - URL: css/main.css
      - URL: css/rad-icons.css
      - URL: css/custom.css
    js:
      - URL: js/rad-animations.js
      - URL: js/sticky-header.js
      - URL: js/library/fontfaceobserver.js
  sections:
    - showcase
    - about
    - client-and-work
    - experience
    - education
    - contact
menu:
  footer:
    - URL: '#about'
      name: About
      weight: 2
    - URL: '#portfolio'
      name: Portfolio
      weight: 3
    - URL: '#contact'
      name: Contacto
      weight: 4
  header:
    - URL: '#about'
      name: About
      weight: 2
    - URL: '#portfolio'
      name: Portfolio
      weight: 3
    - URL: '#contact'
      name: Contacto
      weight: 4
